name: Build Nuxeo Sample Common Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: s4u/maven-settings-action@v2.4.0
      with:
        mirrors: '[{"id": "maven-internal", "name": "Nuxeo mirrors", "mirrorOf": "*,!nuxeo-studio", "url": "https://packages.nuxeo.com/repository/maven-internal"}]'
        servers: |
          [{
              "id": "maven-internal",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_PASSWORD }}"
            },
            {
              "id": "nuxeo-studio",
              "username": "${{ secrets.STUDIO_USERNAME }}",
              "password": "${{ secrets.STUDIO_PASSWORD }}"
          }]
    - name: Build with Maven (skip tests and docker build)
      run: mvn -DskipTests -DskipDocker clean install
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
    - name: Login to Nexus Docker repository
      uses: docker/login-action@v1
      with:
        registry: docker-private.packages.nuxeo.com
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_TOKEN }}
    - name: Determine if should push
      id: should_push
      run: |
        if [[ '${{ github.event_name }}' == 'push' || '${{ contains(github.event.pull_request.labels.*.name, 'docker_push') }}' == 'true' ]]
        then
            echo "Should push docker image"
            echo "::set-output name=should::true"
        else
            echo "Should *not* push docker image: maybe add the label 'docker_push' to the PR"
            echo "::set-output name=should::false"
        fi
    - name: Define docker tag
      id: docker_tag
      run: |
        if [ $EVENT_NAME == 'pull_request' ]
        then
            echo "::set-output name=tag::latest-$BRANCH_NAME"
        else
            echo "::set-output name=tag::latest"
        fi
      env:
        EVENT_NAME: ${{ github.event_name }}
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
    - name: Login to GCR
      uses: docker/login-action@v1
      if: steps.should_push.outputs.should == 'true'
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
        logout: false
    - name: Docker Build Image (and maybe push)
      uses: docker/build-push-action@v2
      with:
        context: ./docker/
        file: ./docker/Dockerfile
        build-args: |
          BASE_IMAGE=docker-private.packages.nuxeo.com/nuxeo/nuxeo:2021.0
          BUILD_TAG=latest
          SCM_REF=built-on-github
          VERSION=1.0
          CLID=${{ secrets.CLID }}
        tags: gcr.io/jx-preprod/nuxeo-sample-multi-common:${{ steps.docker_tag.outputs.tag }}
        push: ${{ steps.should_push.outputs.should }}
